"""
HOI4 Modding Studio - Event Effects Catalog

Categorized list of event effects for the event builder and focus tree editor.
"""

from __future__ import annotations


TECHNOLOGY_CATEGORIES: tuple[str, ...] = (
    "air_doctrine",
    "air_equipment",
    "armor",
    "artillery",
    "asw_tech",
    "base_strike_main",
    "battlefield_support_tree",
    "bb_tech",
    "bc_tech",
    "ca_tech",
    "cas_bomber",
    "cat_air_bombs",
    "cat_air_engine",
    "cat_air_guns",
    "cat_anti_air",
    "cat_anti_tank",
    "cat_armored_cars",
    "cat_base_strike",
    "cat_battlefield_support",
    "cat_deep_battle",
    "cat_fleet_in_being",
    "cat_fortification",
    "cat_grand_battle_plan",
    "cat_heavy_armor",
    "cat_heavy_fighter",
    "cat_light_armor",
    "cat_marines_doctrine",
    "cat_maritime_patrol",
    "cat_mass_assault",
    "cat_mass_mobilization",
    "cat_mechanized_equipment",
    "cat_medium_armor",
    "cat_mobile_warfare",
    "cat_mountaineers_doctrine",
    "cat_operational_integrity",
    "cat_paratroopers_doctrine",
    "cat_production",
    "cat_rangers_doctrine",
    "cat_scout_plane",
    "cat_ship_heavy_battery",
    "cat_ship_light_battery",
    "cat_ship_medium_battery",
    "cat_special_forces_generic",
    "cat_strategic_destruction",
    "cat_strategic_bomber",
    "cat_superior_firepower",
    "cat_synth_oil",
    "cat_synth_rubber",
    "cat_torpedoes",
    "cat_trade_interdiction",
    "computing_tech",
    "concentrated_industry_category",
    "construction_tech",
    "convoy_defense_tree",
    "cv_tech",
    "dd_tech",
    "decryption_tech",
    "dispersed_industry_category",
    "electronics",
    "encryption_tech",
    "engineers_tech",
    "excavation_tech",
    "fleet_in_being_tree",
    "heavy_air",
    "helicopter_tech",
    "hospital_tech",
    "industry",
    "infantry_tech",
    "infantry_weapons",
    "jet_technology",
    "land_doctrine",
    "light_air",
    "light_fighter",
    "logistics_tech",
    "maintenance_company_tech",
    "marine_tech",
    "medium_air",
    "military_police_tech",
    "mio_cat_all_artillery_equipment",
    "mio_cat_all_cas_and_modules",
    "mio_cat_all_heavy_aircraft_and_modules",
    "mio_cat_all_light_aircraft_and_modules",
    "mio_cat_all_light_fighter_and_modules",
    "mio_cat_all_medium_aircraft_and_modules",
    "mio_cat_all_naval_bomber_and_modules",
    "mio_cat_artillery",
    "mio_cat_tech_all_armor_and_modules",
    "mio_cat_tech_all_capital_ship_and_modules",
    "mio_cat_tech_all_carrier_and_modules",
    "mio_cat_tech_all_cruiser_and_modules",
    "mio_cat_tech_all_destroyer_and_modules",
    "mio_cat_tech_all_motorized_mechanized",
    "mio_cat_tech_all_screen_ship_and_modules",
    "mio_cat_tech_all_submarine_and_modules",
    "mio_cat_tech_heavy_armor_and_modules",
    "mio_cat_tech_light_armor_and_modules",
    "mio_cat_tech_medium_armor_and_modules",
    "mot_rockets",
    "motorized_equipment",
    "mountaineers_tech",
    "naval_air",
    "naval_armor",
    "naval_artillery",
    "naval_bomber",
    "naval_doctrine",
    "naval_equipment",
    "naval_minelaying",
    "naval_mines",
    "naval_minesweeping",
    "night_vision",
    "nuclear",
    "operational_integrity_tree",
    "para_tech",
    "plane_modules_tech",
    "pykrete_tech",
    "radar_tech",
    "rangers_tech_cat",
    "recon_tech",
    "rocketry",
    "shbb_tech",
    "ship_modules_tech",
    "signal_company_tech",
    "special_forces_doctrine",
    "ss_tech",
    "strategic_destruction_tree",
    "submarine_doctrine",
    "support_tech",
    "synth_resources",
    "tactical_bomber",
    "tp_tech",
    "trade_interdiction_tree",
    "train_tech",
    "transport_planes_cat",
)


EFFECT_CATEGORIES: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "Political",
        [
            ("Political Power (+100)", "add_political_power = 100"),
            ("Political Power (+200)", "add_political_power = 200"),
            ("Stability (+5%)", "add_stability = 0.05"),
            ("Stability (+10%)", "add_stability = 0.10"),
            ("War Support (+5%)", "add_war_support = 0.05"),
            ("War Support (+10%)", "add_war_support = 0.10"),
            ("National Unity (+10%)", "add_national_unity = 0.1"),
        ],
    ),
    (
        "Ideology",
        [
            (
                "Add Popularity (democratic)",
                "add_popularity = { ideology = democratic popularity = 0.1 }",
            ),
            (
                "Add Popularity (fascism)",
                "add_popularity = { ideology = fascism popularity = 0.1 }",
            ),
            (
                "Add Popularity (communism)",
                "add_popularity = { ideology = communism popularity = 0.1 }",
            ),
            (
                "Add Popularity (neutrality)",
                "add_popularity = { ideology = neutrality popularity = 0.1 }",
            ),
            (
                "Set Ruling Party (democratic)",
                "set_politics = { ruling_party = democratic }",
            ),
            ("Set Ruling Party (fascism)", "set_politics = { ruling_party = fascism }"),
            (
                "Set Ruling Party (communism)",
                "set_politics = { ruling_party = communism }",
            ),
            (
                "Set Ruling Party (neutrality)",
                "set_politics = { ruling_party = neutrality }",
            ),
        ],
    ),
    (
        "Economy",
        [
            (
                "Civilian Factory (+1)",
                "add_building_construction = { type = industrial_complex level = 1 instant_build = yes }",
            ),
            (
                "Military Factory (+1)",
                "add_building_construction = { type = arms_factory level = 1 instant_build = yes }",
            ),
            (
                "Infrastructure (+1)",
                "add_building_construction = { type = infrastructure level = 1 instant_build = yes }",
            ),
            (
                "Synthetic Refinery (+1)",
                "add_building_construction = { type = synthetic_refinery level = 1 instant_build = yes }",
            ),
            (
                "Nuclear Reactor (+1)",
                "add_building_construction = { type = nuclear_reactor level = 1 instant_build = yes }",
            ),
            (
                "Radar Station (+1)",
                "add_building_construction = { type = radar_station level = 1 instant_build = yes }",
            ),
            (
                "Bunker (+1)",
                "add_building_construction = { type = bunker level = 1 instant_build = yes }",
            ),
            (
                "Coastal Fortress (+1)",
                "add_building_construction = { type = coastal_bunker level = 1 instant_build = yes }",
            ),
        ],
    ),
    (
        "Military",
        [
            ("Army Experience (+10)", "add_army_experience = 10"),
            ("Navy Experience (+10)", "add_navy_experience = 10"),
            ("Air Experience (+10)", "add_air_experience = 10"),
            ("Command Power (+25)", "add_command_power = 25"),
            ("Manpower (+50k)", "add_manpower = 50000"),
            ("Manpower (+100k)", "add_manpower = 100000"),
            ("Fuel (+500)", "add_fuel = 500"),
            (
                "Add Equipment",
                "add_equipment_to_stockpile = { type = infantry_equipment_0 count = 1000 }",
            ),
        ],
    ),
    (
        "Diplomacy",
        [
            ("Create Faction", 'create_faction = "My Faction"'),
            ("Join Faction", "country_event = { id = generic.5 }"),
            ("Leave Faction", "leave_faction = yes"),
            ("White Peace (all)", "white_peace = all"),
            (
                "Add Opinion (+)",
                "add_opinion_modifier = { target = FROM modifier = positive_relation }",
            ),
            (
                "Add Opinion (-)",
                "add_opinion_modifier = { target = FROM modifier = negative_relation }",
            ),
        ],
    ),
    (
        "Territory",
        [
            ("Transfer State", "transfer_state = 123"),
            ("Add Core to State", "123 = { add_core_of = TAG }"),
            ("Remove Core from State", "123 = { remove_core_of = TAG }"),
            (
                "Annex Country",
                "annex_country = { target = FROM transfer_troops = yes }",
            ),
            ("Puppet Country", "puppet = FROM"),
            ("Release Puppet", "release_puppet = FROM"),
            ("Set Capital", "set_capital = 123"),
        ],
    ),
    (
        "War Goals",
        [
            (
                "Wargoal (Annex)",
                "create_wargoal = { type = take_state_focus target = ROOT generator = { 123 } }",
            ),
            (
                "Wargoal (Puppet)",
                "create_wargoal = { type = puppet_wargoal_focus target = FROM generator = { all } }",
            ),
            (
                "Wargoal (Liberate)",
                "create_wargoal = { type = liberate_wargoal target = FROM generator = { all } }",
            ),
            (
                "Wargoal (Force Ideology)",
                "create_wargoal = { type = force_government_type target = FROM government_type = democratic }",
            ),
            (
                "Wargoal (Take Claims)",
                "create_wargoal = { type = take_claimed_state target = FROM generator = { all } }",
            ),
        ],
    ),
    (
        "Technology",
        [
            ("Research Slot (+1)", "add_research_slot = 1"),
            (
                "Free Infantry Weapons Tech Bonus",
                "add_tech_bonus = { bonus = 1.0 category = infantry_weapons }",
            ),
            (
                "Free Industry Tech Bonus",
                "add_tech_bonus = { bonus = 1.0 category = industry }",
            ),
            (
                "Free Land Doctrine Tech Bonus",
                "add_tech_bonus = { bonus = 1.0 category = land_doctrine }",
            ),
        ],
    ),
    (
        "Custom",
        [
            ("Custom Effect", "# Add your custom effect here"),
        ],
    ),
]
